### ISSUE TITLE
Perplexity numbers for masking rates reported in Table 3. 

### ISSUE THREAD

**Issue by raotnameh** [princeton-nlp/DinkyTrain#10]
Hi, 

Thanks for the wonderful work. I was wondering, if you have the PPL for all the masking rates reported in Table 3? 

Thanks
@CodeCreator @gaotianyu1350 @danqi @a3616001

**Comment by gaotianyu1350** [comment]
Hi,

We didn't test all those models for PPL. However, you can download all of them from our GitHub repo and evaluate them.
