### ISSUE TITLE
Why do you use last checkpoint for validation rather than best checkpoint?

### ISSUE THREAD

**Issue by BaohaoLiao** [princeton-nlp/DinkyTrain#3]
Hi,

in your script https://github.com/princeton-nlp/DinkyTrain/blob/main/finetune_glue.sh, it seems you use last checkpoint to validate. May I ask why don't you use the best checkpoint?

In addition, if you use the last checkpoint to validate, does it means that you also use it to test?

**Comment by gaotianyu1350** [comment]
Hi,

Since in our grid search we also control the number of epochs, we just use the last checkpoint for evaluation. 

Another reason is that due to the large volume of experiments we need to do, we just save the last checkpoint and skip any intermediate checkpoints to save time.

**Comment by BaohaoLiao** [comment]
According to my observation, the best performance is not always obtained by the last epoch. When the epoch number increases, like 5 or 10, this happens more often.

**Comment by gaotianyu1350** [comment]
Thanks for letting us know your observation. It is possible that the last epoch does not always obtain the best results. However, given the extensive grid search hyper parameters we use, the final results should be near optimal.

**Comment by BaohaoLiao** [comment]
I see. I will try to analyze the performance difference of the best checkpoint and last checkpoint, and let you know if I have new findings.
